### ISSUE TITLE
Add to regro landing page

### ISSUE THREAD

**Issue by scopatz** [regro/conda-mirror#4]
We should add conda-mirror to the regro landing page: https://regro.github.io/

The source for this is at https://github.com/regro/regro.github.io.

@xhochy, would you mind taking a stab at this, please?  We probably should also have an icon for conda-mirror (and maybe docs?)

**Comment by jakirkham** [comment]
Probably would be good to update [the package url]( https://github.com/regro/conda-mirror/blob/912b92008001853ca2f7540e772db31a8754a218/setup.py#L21 ) as well

**Comment by scopatz** [comment]
Very true!
